POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "John Doe 2",
  "dateOfBirth": "1980-01-01",
  "ssn": "123-45-6789",
  "gender": "male",
  "occupation": "engineer"
}