POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
"date": "2015-01-02",
"type": "Hospital",
"specialist": "MD Test",
"description": "This is just a test.",
"discharge": {
"date": "2015-01-16",
"criteria": "Thumb fully healed."
}
}